# Generated by Django 3.2.6 on 2021-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=999)),
                ('vip_point', models.IntegerField()),
                ('website_url', models.CharField(max_length=999, null=True)),
                ('timestamp', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='ImportantTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=999)),
                ('vip_point', models.IntegerField()),
                ('tweet', models.CharField(max_length=999)),
                ('timestamp', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=999)),
                ('follower_count', models.IntegerField()),
                ('account_creation_date', models.CharField(max_length=999)),
                ('website_url', models.CharField(max_length=999, null=True)),
                ('timestamp', models.CharField(max_length=999)),
            ],
        ),
    ]
