# Generated by Django 3.2.6 on 2021-08-30 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportantPerson',
            new_name='Important_Person',
        ),
        migrations.RenameModel(
            old_name='ImportantTweet',
            new_name='Important_Tweet',
        ),
        migrations.RenameModel(
            old_name='NewAccount',
            new_name='New_Account',
        ),
    ]
