# Generated by Django 3.2.6 on 2021-08-30 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20210830_0810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Important_Person',
            new_name='ImportantPerson',
        ),
        migrations.RenameModel(
            old_name='Important_Tweet',
            new_name='ImportantTweet',
        ),
        migrations.RenameModel(
            old_name='New_Account',
            new_name='NewAccount',
        ),
        migrations.AlterModelTable(
            name='importantperson',
            table='"scraper_important_person"',
        ),
        migrations.AlterModelTable(
            name='importanttweet',
            table='"scraper_important_tweet"',
        ),
        migrations.AlterModelTable(
            name='newaccount',
            table='"scraper_new_account"',
        ),
    ]
